language: node_js
node_js:
  - stable
cache:
  npm: true
  directories:
    - firestore/node_modules
    - frontend/node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_155663baf9b1_key -iv $encrypted_155663baf9b1_iv
    -in firebase-config.json.enc -out firebase-config.json -d
jobs:
  include:
    - stage: Tests
      name: firestore rules
      script:
        - npm i -g firebase firebase-tools
        - firebase setup:emulators:firestore
        - npm install --prefix ./firestore/
        - npm run firestore-test --prefix ./firestore/
    - script:
        - npm install --prefix ./frontend/
        - npm run test --prefix ./frontend/
      name: frontend
    - stage: deploy
      script:
        - npm install --prefix ./functions/
        - npm run build --prefix ./functions/
        - npm run build  --prefix ./frontend/
      if: branch = master OR branch = develop
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: mXL9QeO/smdF5nlGwoIua+bryn3Td00b5KPwoE9OCgHrl4KWyb/9BgUHQ1q78ezUV0s9wPFZCghIKi2VMuCWNyeAchN9+/EuuzSr4rZRN48rTw+MT6elLGvmaP4NM3kryyFfnaWxh+VFmjgjEHTSXuCtYIpJIPFR9FKZzzI1v1cjry04RyyyEXwnBcTShEZUuATJdDXnEKi2Hu/HGuVUpacAUxH/tSLdLL8AwWm/Ei4QY8uba5BRuaiJgt+NRnudJcCBSdoEfeuvroml4ZT3k/LGy4xZgBR8D/CtsykFNBon6R/CsXBuktpuPBmsgsol0zYmX0jw0gsoJ1AGLTz2ATjYdvKAefo/KESpHt628lCRJlg2ZB7Cn6T3ZKddTfxqDCaCptUmxkO6MFzxvO2y9rGNsaZVLYNp/POpJDTSXb5EuhSyPhfPDKFiNypVF3ONQIfOxZokCT7EM/MGlvXjmo1GHiyv2hHiTeTh7uL8yfPuZAIxpEHw45H++TplLwsWbUhIjHqD0l5gCIEyN7jKKjfKDTMVdH3ZDsMM3ijUneQu62yNlM6jDW6c+z8rg+M7DFBo53be3XLqZ8Y1cWe+38bX2LYWsG6wdio3K4j2s3/x78rZluDEK8e9VYGpeMfNdLT79aKsqNeMsyLiQ8XlB4OrtqF6ZQJgkuIf4VFc3xA=
        on:
          branch: master
