import React from "react";
import { useSelector } from "react-redux";
import {
  facesSelector,
  facesLoadingSelector,
} from "../../store/faces/selectors";
import { CircularProgress, Grid, Hidden, Modal } from "@material-ui/core";
import styled from "styled-components";
import FaceListItem from "./FaceListItem";
import FaceModal from "./FaceModal";

const CenteredCicularProgress = styled(CircularProgress)`
  display: block;
  margin: auto;
`;

/**
 * Component to display all faces generated by the user.
 */
const FacesList = () => {
  const faces = useSelector(facesSelector);
  const facesLoading = useSelector(facesLoadingSelector);

  // Store index of face to display in modal, on mobile only.
  const [faceIndex, setFaceIndex] = React.useState<number | undefined>(
    undefined
  );

  if (facesLoading) {
    return <CenteredCicularProgress />;
  }

  if (!faces || faces.length === 0) {
    return <div>No Faces yet</div>;
  }

  return (
    <>
      <Grid container spacing={3}>
        {faces.map((f, i) => (
          <Grid item xs={4} key={f.id}>
            <FaceListItem f={f} openFaceModal={() => setFaceIndex(i)} />
          </Grid>
        ))}
      </Grid>
      {/* Modal for mobile only, displays the current selected faceIndex. */}
      <Hidden smUp>
        <Modal
          aria-labelledby="simple-modal-title"
          aria-describedby="simple-modal-description"
          open={faceIndex !== undefined}
          onClose={() => setFaceIndex(undefined)}
        >
          {faceIndex !== undefined ? <FaceModal f={faces[faceIndex]} /> : <></>}
        </Modal>
      </Hidden>
    </>
  );
};

export default FacesList;
