# Adapted from https://github.com/treosh/lighthouse-ci-action
name: Lighthouse CI
on:
  push:
    branches:
      - master
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://facegen-fc9de.web.app/
            https://facegen-fc9de.web.app/predict/
          budgetPath: ./budget.json
          configPath: "./lighthouserc.json"
          runs: 3
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
